## 1.Write a Python Program to Add Two Matrices?
### Ans:

In [1]:
X = [[18,12,15],
    [10,20,30],
    [5,10,15]]

Y = [[12,18,15],
    [20,10,0],
    [25,20,15]]

ans = [[0,0,0],
      [0,0,0],
      [0,0,0]]

for i in range(len(X)):
    for j in range(len(X[0])):
        ans[i][j] = X[i][j] + Y[i][j]
                
for h in ans:
    print(h)
            
    

[30, 30, 30]
[30, 30, 30]
[30, 30, 30]


## 2.Write a Python Program to Multiply Two Matrices?
### Ans:

In [2]:
# 3x3 matrix
A = [[2,5,9],
    [4,8,3],
    [7,5,3]]

# 3x4 matrix
B = [[1,2,3,4],
    [7,8,9,4],
    [5,2,3,6]]

# result will be 3x4 matrix
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]

result = np.dot(A,B)
for i in result:
    print(i)

<IPython.core.display.Javascript object>

[82 62 78 82]
[75 78 93 66]
[57 60 75 66]


## 3.Write a Python Program to Transpose a Matrix?
### Ans:

In [3]:
A = [[82,62,78,82],
    [75,78,93,66],
    [57,60,75,66]]

transA = [[0,0,0],
         [0,0,0],
         [0,0,0],
         [0,0,0],]

for a in range(len(A)):
    for b in range(len(A[0])):
        transA[b][a] = A[a][b]
        
for g in transA:
    print(g)
        

[82, 75, 57]
[62, 78, 60]
[78, 93, 75]
[82, 66, 66]


## 4.Write a Python Program to Sort Words in Alphabetic Order?
### Ans:

In [4]:
mystr = input("Enter the string: ")
x = mystr.split()
x.sort()
for j in x:
    print(j)

Enter the string: proud to be an indian
an
be
indian
proud
to


## 5.Write a Python Program to Remove Punctuation From a String?
### Ans:

In [5]:
str_punc = " abc is great!, & and @xyt is shit.; "
print("The original string is : " + str_punc)
str_ = re.sub(r'[^\w\s]', '', str_punc)
str_
print("The string after punctuation filter : " + str_)

The original string is :  abc is great!, & and @xyt is shit.; 


<IPython.core.display.Javascript object>

The string after punctuation filter :  abc is great  and xyt is shit 
